INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Adam', 'Nowak', '685483342', 'adamnowak@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Kamil', 'Serek', '758463251', 'kamilserek@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Pawel', 'Golacz', '765847578', 'pawelgolacz@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Piotr', 'Rusek', '884542154', 'piotrrusek@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Mateusz', 'Tasiemiec', '648758485', 'mateusztasiemiec@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Andrzej', 'Kowalski', '666958748', 'andrzejkowalski@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Adrian', 'Jopek', '745487984', 'adrianjopek@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Karol', 'Daniec', '774774744', 'karoldaniec@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Patryk', 'Oleksy', '765454659', 'patrykoleksy@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Jerzy', 'Duda', '665484745', 'jerzyduda@op.pl', 'Haslo123!');
INSERT INTO client (first_name, surname, phone_number, email, password) VALUES ('Jarosław', 'Garbowicz', '665874145', 'jaroslawgarbowicz@op.pl', 'Haslo123!');

INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Pruszkowska', '13C', '21', '01-231', 'Warszawa', 1);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Katowicka', '5B', '123', '04-264', 'Warszawa', 2);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Nowatorska', '2', '43', '00-102', 'Warszawa', 3);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Czumy', '64', '1', '02-112', 'Warszawa', 4);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Czluchowska', '12', '421', '05-221', 'Warszawa', 5);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Wilanowska', '31', '12', '02-231', 'Warszawa', 6);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Piastowa', '421', '112', '01-221', 'Warszawa', 7);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Kocjana', '41', '121', '05-521', 'Warszawa', 8);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Literacka', '14', '2', '03-421', 'Warszawa', 9);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Powstancow Slaskich', '15', '1', '03-433', 'Warszawa', 10);
INSERT INTO address (street_name, building_number, apartment_number, postal_code, city, client_id) VALUES ('Marymoncka', '1', '42', '06-223', 'Warszawa', 11);

INSERT INTO employee (first_name, surname, phone_number, email, password, employment_date, job_position, salary) VALUES ('Mariusz', 'Bober', '766545545', 'mariuszbober@op.pl', 'Haslo123!', '2017-09-01', 'Pracownik', 3600);
INSERT INTO employee (first_name, surname, phone_number, email, password, employment_date, job_position, salary) VALUES ('Marek', 'Nosal', '665487548', 'mareknosal@op.pl', 'Haslo123!', '2015-02-01', 'Pracownik', 4500);
INSERT INTO employee (first_name, surname, phone_number, email, password, employment_date, job_position, salary) VALUES ('Michal', 'Balak', '746352412', 'michalbalak@op.pl', 'Haslo123!', '2014-07-01', 'Pracownik', 5400);
INSERT INTO employee (first_name, surname, phone_number, email, password, employment_date, job_position, salary) VALUES ('Rafal', 'Norek', '666669874', 'rafalnorek@op.pl', 'Haslo123!', '2013-03-01', 'Kierownik', 6300);
INSERT INTO employee (first_name, surname, phone_number, email, password, employment_date, job_position, salary) VALUES ('Konrad', 'Borowicz', '611211311', 'konradborowicz@op.pl', 'Haslo123!', '2010-04-01', 'Prezes', 11000);

INSERT INTO animal (name, type, birth_date) VALUES ('Benek', 'DOG', '2017-09-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Rocky', 'CAT', '2019-01-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Szynka', 'DOG', '2020-11-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Pasztet', 'DOG', '2021-12-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Alfons', 'CAT', '2016-11-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Champion', 'CAT', '2015-10-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Jabcok', 'CAT', '2017-08-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Alkus', 'RABBIT', '2018-05-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Rurek', 'DOG', '2017-05-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Antek', 'RABBIT', '2019-12-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Bobek', 'RABBIT', '2019-03-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Jurek', 'CAT', '2021-05-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Kalina', 'DOG', '2021-02-01');
INSERT INTO animal (name, type, birth_date) VALUES ('Misia', 'BIRD', '2013-03-01');

INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2014-10-11 10:00:00', 1, 1, 1);
INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2015-11-02 10:00:00', 2, 2, 2);
INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2016-11-17 10:00:00', 4, 4, 1);
INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2017-10-18 10:00:00', 5, 5, 2);
INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2018-08-11 10:00:00', 6, 6, 3);
INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2019-07-03 10:00:00', 8, 6, 3);
INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2020-03-05 10:00:00', 9, 8, 4);
INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2021-01-08 10:00:00', 12, 10, 1);
INSERT INTO adoption (adoption_date, animal_id, client_id, employee_id) VALUES ('2021-10-23 10:00:00', 13, 11, 2);
